baseURL = 'https://readerflow.app'
languageCode = 'en-us'
title = 'ReaderFlow - Your Personal Read-It-Later App'
theme = 'readerflow'

[params]
  description = "A beautiful, offline-first read-it-later app that keeps your articles synced across all your devices."
  author = "ReaderFlow Team"
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Navigation menu - now managed in data/content.yaml
# You can reference .Site.Data.content.navigation in templates
[menu]
  [[menu.main]]
    name = "Features"
    url = "#features"
    weight = 10
  [[menu.main]]
    name = "Import"
    url = "#csv-import"
    weight = 20
  [[menu.main]]
    name = "Download"
    url = "#download"
    weight = 30
